language: python

python:
- '3.6'

cache: pip

git:
  depth: false

install:
- pip3 install -r requirements-dev.txt
- python3 setup.py develop
- python3 -m spacy download en

script:
- pytest -v -m "not gpu_only and not slow"